### ISSUE TITLE
Crashed While Downloading Firmware

### ISSUE THREAD

**Issue by Keeboy99** [Glumboi/GlumSak#25]
GlumSak Version 2.3.2.2 Crashed:

Short version: Access to the path 'C:\Users\Keebo\AppData\Roaming\Ryujinx\bis\system\contents\registered\02b1dd519a6df4de1b11871851d328a1.nca' is denied.

Detailed Error: System.UnauthorizedAccessException: Access to the path 'C:\Users\Keebo\AppData\Roaming\Ryujinx\bis\system\contents\registered\02b1dd519a6df4de1b11871851d328a1.nca' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.Compression.ZipFileExtensions.ExtractToFile(ZipArchiveEntry source, String destinationFileName, Boolean overwrite)
   at EmuSak_Revive.Network.Networking.Unzip(String inputFile, String outPath, Boolean deleteAfterDone, Boolean filesInFolder, String childFolderName)
   at EmuSak_Revive.Network.Networking.Client_DownloadFileCompleted(Object sender, AsyncCompletedEventArgs e)
   at System.Net.WebClient.OnDownloadFileCompleted(AsyncCompletedEventArgs e)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by Glumboi** [comment]
Try running as admin. I am already investigating Crashes related to Downloads but the fixes will probably come with GlumSak3.
