### ISSUE TITLE
Crashing when clicking "Ryujinx" en can't open "Yuzu"

### ISSUE THREAD

**Issue by ghost** [Glumboi/GlumSak#35]
I get a notification if I try to open the Yuzu config:
Could not load Yuzu, please make sure you ran Yuzu before... (I have already opened it lol)

When clicking the Ryujinx config I get this:
GlumSak Version 2.5.1.1 Crashed:

Short version: The system cannot find the file specified

Detailed Error: System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at EmuSak_Revive.Emulators.Yuzu.GetYuzuBinaryVersion(String path)
   at EmuSak_Revive.GUI_WPF.MainWindow.<>c__DisplayClass35_0.<CheckForYuzuUpdate>b__1()
   at System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback)
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EmuSak_Revive.GUI_WPF.MainWindow.<CheckForYuzuUpdate>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at EmuSak_Revive.GUI_WPF.App.Main()

**Comment by Glumboi** [comment]
Do you have a portable yuzu install?

**Comment by ghost** [comment]
No, just the standalone version from the website. I know that I should set a path in the settings if I'm using the portable one, but does that also apply to the standalone version?

**Comment by Glumboi** [comment]
If standalone means the standard install of yuzu, then you dont have to set it in the seeings. Although you could try that and see if it does fix the issue. Another fix might be running GlumSak as admin but if using the shortcuts on the desktop or start menu it will already launch as admin.

**Comment by ghost** [comment]
Yeah, that's what meant. I'm already launching it as admin so that's not the issue. I could try and set a path in the settings.

**Comment by ghost** [comment]
I reinstalled the whole damn thing and removed all the old files (in Program Files (x86), AppData > Local, and AppData > Roaming) and now the program will start up when clicking on the Ryujinx config. So that's one issue fixed.
It still can't detect Yuzu though. I tried to set the path but it's refuses to open. Same message. same problem.

**Comment by Glumboi** [comment]
Ima take a note and will look into it
